In [28]:
import pickle
import pprint

# load database.pickle
filename = "testcases/database.pickle"
with open(filename, "rb") as f:
    database = pickle.load(f)

# show the data structure of database
"""
Data structure of database:

database: dict
{
    <calc_name>:{
        <method_0>: <Molecules object>,
        <method_1>: <Molecules object>,
        
    },

}

"""
pprint.pprint(database)


{'Alkoxyl': {'B3LYP': Molecules(symbols='CCl2F2CHO', pbc=False),
             'G4': Molecules(symbols='CCl2F2CHO', pbc=False),
             'MP2,MP2(FC)': Molecules(symbols='CCl2F2CHO', pbc=False)},
 'Alkoxyl-ClLeave-CF2ClCH0': {'B3LYP': Molecules(symbols='CF2CHOCl', pbc=False),
                              'G4': Molecules(symbols='CF2CHOCl', pbc=False),
                              'MP2,MP2(FC)': Molecules(symbols='CF2CHOCl', pbc=False)},
 'Alkoxyl-ClLeave_ts': {'B3LYP': Molecules(symbols='CClF2CHOCl', pbc=False),
                        'G4': Molecules(symbols='CClF2CHOCl', pbc=False),
                        'MP2,MP2(FC)': Molecules(symbols='CClF2CHOCl', pbc=False)},
 'Alkoxyl-HLeave-CClF2C(O)Cl': {'B3LYP': Molecules(symbols='CCl2F2CO', pbc=False),
                                'G4': Molecules(symbols='CCl2F2CO', pbc=False),
                                'MP2,MP2(FC)': Molecules(symbols='CCl2F2CO', pbc=False)},
 'Alkoxyl-HLeave_O2_ts': {'B3LYP': Molecules(symbols='CCl2F2CHO3',

In [31]:
# some setting for pretty printing
import numpy as np
import pandas as pd
np.set_printoptions(precision=3)
pd.set_option("display.chop_threshold", 3)
pd.set_option('display.width', 80)
pd.set_option('display.max_rows', 10)
pd.set_option('display.max_columns', 6)


# show one example in data
print(database["HCFC132b-Cl_ts"])
mol = database["HCFC132b-Cl_ts"]["B3LYP"] # G4 or MP2,MP2(FC) or B3LYP
print(type(mol))
# Molecules is an object storing g16 calculation results
# show the basic information (inherited from ase.Atoms)
print(f"Formula: {mol.get_chemical_formula()}")
print(f"Sybmols: {mol.get_chemical_symbols()}")
print("Geometry:")
print(mol.get_positions())


# show the calculation infomation
print(f"Method: {mol.method}")
# print(f"Basis sets: {mol.basis}") # Bugs
print(f"Electronic energy(hartree): {mol.electronic_energy}")
print(f"Is TS calculation? {mol.ts}")
print("Frequencies(cm-1):")
print(mol.frequencies)
print(f"ZPE(hartree): {mol.zpe}")
print(f"Anharmonic ZPE(hartree): {mol.anharm_zpe}")
print("Anharminic matrix:")
print(pd.DataFrame(mol.anharm_matrix))


{'MP2,MP2(FC)': Molecules(symbols='CH2CCl2F2Cl', pbc=False), 'B3LYP': Molecules(symbols='CH2CCl2F2Cl', pbc=False), 'G4': Molecules(symbols='CH2CCl2F2Cl', pbc=False)}
<class 'gausskit.molecules.Molecules'>
Formula: C2H2Cl3F2
Sybmols: ['C', 'H', 'H', 'C', 'Cl', 'Cl', 'F', 'F', 'Cl']
Geometry:
[[-0.228  0.549 -0.619]
 [-1.253 -0.364 -0.274]
 [-0.174  0.394 -1.694]
 [ 0.993  0.101  0.168]
 [ 1.504 -1.524 -0.399]
 [-0.829  2.106 -0.177]
 [ 2.006  0.955 -0.028]
 [ 0.737  0.056  1.471]
 [-2.318 -1.318  0.005]]
Method: B3LYP
Electronic energy(hartree): -1657.63816878
Is TS calculation? True
Frequencies(cm-1):
[3175.91  1286.637 1236.571 1164.302 1069.132  978.483  879.5    867.367
  828.09   785.361  568.438  453.277  425.175  386.394  298.825  274.917
  170.271  124.262   69.968   40.478 -986.86 ]
ZPE(hartree): 0.034362
Anharmonic ZPE(hartree): 0.03336601834563088
Anharminic matrix:
          0        1        2   ...       18       19         20
0  -59.61720 -8.11372  0.00000  ...  0.00000  