In [1]:
import pickle
import pprint

# load database.pickle
filename = "testcases/database.pickle"
with open(filename, "rb") as f:
    database = pickle.load(f)

# show the data structure of database
pprint.pprint(database)


{'Alkoxyl': {'B3LYP': Molecules(symbols='CCl2F2CHO', pbc=False),
             'G4': Molecules(symbols='CCl2F2CHO', pbc=False),
             'MP2': Molecules(symbols='CCl2F2CHO', pbc=False)},
 'Alkoxyl-ClLeave-CF2ClCH0': {'B3LYP': Molecules(symbols='CF2CHOCl', pbc=False),
                              'G4': Molecules(symbols='CF2CHOCl', pbc=False),
                              'MP2': Molecules(symbols='CF2CHOCl', pbc=False)},
 'Alkoxyl-ClLeave_ts': {'B3LYP': Molecules(symbols='CClF2CHOCl', pbc=False),
                        'G4': Molecules(symbols='CClF2CHOCl', pbc=False),
                        'MP2': Molecules(symbols='CClF2CHOCl', pbc=False)},
 'Alkoxyl-HLeave-CClF2C(O)Cl': {'B3LYP': Molecules(symbols='CCl2F2CO', pbc=False),
                                'G4': Molecules(symbols='CCl2F2CO', pbc=False),
                                'MP2': Molecules(symbols='CCl2F2CO', pbc=False)},
 'Alkoxyl-HLeave_O2_ts': {'B3LYP': Molecules(symbols='CCl2F2CHO3', pbc=False),
                   

In [3]:
# some setting for pretty printing
import numpy as np
import pandas as pd
np.set_printoptions(precision=3)
pd.set_option("display.chop_threshold", 3)
pd.set_option('display.width', 80)
pd.set_option('display.max_rows', 10)
pd.set_option('display.max_columns', 6)


# show one example in data
print(database["HCFC132b-OH_ts"])
mol = database["HCFC132b-OH_ts"]["MP2_hindrot"] # G4 or MP2,MP2(FC) or B3LYP
# hint:  for  "HCFC132b-OH_ts":
#                 "B3LYP_hindrot":  example with hindered rotor calculation
#                 "B3LYP":          example with anharmonic vibrations
#                 "MP2,MP2(FC)":    example with anharmonic vibrations



# show the basic information (inherited from ase.Atoms)
print(f"Formula: {mol.get_chemical_formula()}")
print(f"Sybmols: {mol.get_chemical_symbols()}")
print("Geometry:")
print(mol.get_positions())


# show the calculation infomation
print(f"Method: {mol.method}")
print(mol.logpath)
# print(f"Basis sets: {mol.basis}") # Bugs
print(f"Electronic energy(hartree): {mol.electronic_energy}")
print(f"Is TS calculation? {mol.ts}")
print("Frequencies(cm-1):")
print(mol.frequencies)
print(f"ZPE(hartree): {mol.zpe}")
print(f"Anharmonic ZPE(hartree): {mol.anharm_zpe}")
print("Anharminic matrix:")
print(pd.DataFrame(mol.anharm_matrix))


# hindered rotor
mol_hindrot = mol.hinderedrotor
if mol_hindrot != []:
    print("Hindered rotor information")
    print("Reduced momentums (amu*Bohr**2)")
    print(mol_hindrot._reduced_moms)
    print("Rotating bond")
    print(mol_hindrot._rotating_bonds)
    print("Rotating atoms")
    print(mol_hindrot._rotating_groups)
    print("In replacement of these vibrations")
    print(mol_hindrot._corrected_vibs)

{'MP2_hindrot': Molecules(symbols='CH2CCl2F2OH', pbc=False), 'MP2': Molecules(symbols='CH2CCl2F2OH', pbc=False), 'B3LYP': Molecules(symbols='CH2CCl2F2OH', pbc=False), 'G4': Molecules(symbols='CH2CCl2F2OH', pbc=False)}
Formula: C2H3Cl2F2O
Sybmols: ['C', 'H', 'H', 'C', 'Cl', 'Cl', 'F', 'F', 'O', 'H']
Geometry:
[[ 0.     0.     0.   ]
 [ 0.     0.     1.211]
 [ 1.041  0.    -0.315]
 [-0.727  1.254 -0.43 ]
 [ 0.19   2.677  0.083]
 [-0.832 -1.44  -0.536]
 [-0.889  1.295 -1.751]
 [-1.944  1.297  0.131]
 [-0.348  0.218  2.414]
 [-1.278  0.44   2.26 ]]
Method: MP2
/home/yuflin/dev/Gausskit/data/HCFC132b-OH_ts.log
Electronic energy(hartree): -1271.4393205249
Is TS calculation? True
Frequencies(cm-1):
[-2204.6    74.3    92.9   142.    177.1   187.8   286.2   310.9   408.5
   446.6   566.    733.9   772.2   821.4   873.8   987.6  1063.4  1083.4
  1232.6  1267.5  1327.6  1527.6  3212.1  3814.3]
ZPE(hartree): 0.048777
anharmonic zero point energy is not set
Anharmonic ZPE(hartree): None
Anharminic