In [23]:
import pickle
import pprint

# load database.pickle
filename = "testcases/database.pickle"
with open(filename, "rb") as f:
    database = pickle.load(f)

# show the data structure of database
"""
Data structure of database:

database: dict
{
    <calc_name>:{
        <method_0>: <Molecules object>,
        <method_1>: <Molecules object>,
        
    },

}

"""
pprint.pprint(database)


{'Alkoxyl': {'B3LYP': Molecules(symbols='CCl2F2CHO', pbc=False),
             'G4': Molecules(symbols='CCl2F2CHO', pbc=False),
             'MP2-FC': Molecules(symbols='CCl2F2CHO', pbc=False)},
 'Alkoxyl-ClLeave-CF2ClCH0': {'B3LYP': Molecules(symbols='CF2CHOCl', pbc=False),
                              'G4': Molecules(symbols='CF2CHOCl', pbc=False),
                              'MP2-FC': Molecules(symbols='CF2CHOCl', pbc=False)},
 'Alkoxyl-ClLeave_ts': {'B3LYP': Molecules(symbols='CClF2CHOCl', pbc=False),
                        'G4': Molecules(symbols='CClF2CHOCl', pbc=False),
                        'MP2-FC': Molecules(symbols='CClF2CHOCl', pbc=False)},
 'Alkoxyl-HLeave-CClF2C(O)Cl': {'B3LYP': Molecules(symbols='CCl2F2CO', pbc=False),
                                'G4': Molecules(symbols='CCl2F2CO', pbc=False),
                                'MP2-FC': Molecules(symbols='CCl2F2CO', pbc=False)},
 'Alkoxyl-HLeave_O2_ts': {'B3LYP': Molecules(symbols='CCl2F2CHO3', pbc=False),
       

In [28]:
# some setting for pretty printing
import numpy as np
import pandas as pd
np.set_printoptions(precision=3)
pd.set_option("display.chop_threshold", 3)
pd.set_option('display.width', 80)
pd.set_option('display.max_rows', 10)
pd.set_option('display.max_columns', 6)


# show one example in data
print(database["HCFC132b-OH_ts"])
mol = database["HCFC132b-OH_ts"]["B3LYP_1"] # G4 or MP2,MP2(FC) or B3LYP
mol_1 = database["HCFC132b-OH_ts"]["B3LYP"] # G4 or MP2,MP2(FC) or B3LYP
print(type(mol))
# Molecules is an object storing g16 calculation results
# show the basic information (inherited from ase.Atoms)
print(f"Formula: {mol.get_chemical_formula()}")
print(f"Sybmols: {mol.get_chemical_symbols()}")
print("Geometry:")
print(mol.get_positions())


# show the calculation infomation
print(f"Method: {mol.method}")
print(mol.hinderedrotor())
print(mol_1.hinderedrotor())
print(mol.logpath)
print(mol_1.logpath)
# print(f"Basis sets: {mol.basis}") # Bugs
# print(f"Electronic energy(hartree): {mol.electronic_energy}")
# print(f"Is TS calculation? {mol.ts}")
# print("Frequencies(cm-1):")
print(mol.frequencies)
print(mol_1.frequencies)
print(f"ZPE(hartree): {mol.zpe}")
print(f"ZPE(hartree): {mol_1.zpe}")
# print(f"Anharmonic ZPE(hartree): {mol.anharm_zpe}")
# print("Anharminic matrix:")
# print(pd.DataFrame(mol.anharm_matrix))


{'B3LYP': Molecules(symbols='CH2CCl2F2OH', pbc=False), 'MP2-FC': Molecules(symbols='CH2CCl2F2OH', pbc=False), 'B3LYP_1': Molecules(symbols='CH2CCl2F2OH', pbc=False), 'G4': Molecules(symbols='CH2CCl2F2OH', pbc=False)}
<class 'gausskit.molecules.Molecules'>
Formula: C2H3Cl2F2O
Sybmols: ['C', 'H', 'H', 'C', 'Cl', 'Cl', 'F', 'F', 'O', 'H']
Geometry:
[[ 0.616  0.157 -0.665]
 [ 0.572  1.343 -0.44 ]
 [ 0.45   0.035 -1.734]
 [-0.473 -0.498  0.169]
 [-2.085  0.033 -0.438]
 [ 2.227 -0.405 -0.218]
 [-0.416 -1.828  0.108]
 [-0.365 -0.139  1.455]
 [ 0.328  2.546  0.054]
 [ 0.171  2.314  0.986]]
Method: B3LYP
[]
[11.439  1.864  0.981]
/home/augustus/dev/Gausskit/data/20221023-RP_B3LYP_anharm/HCFC132b/HCFC132b-OH_ts.log
/home/augustus/dev/Gausskit/data/HCFC132b-OH_ts.log
[3734.302 3153.702 1463.225 1289.07  1235.006 1217.785 1093.211 1007.399
  930.601  853.743  781.922  769.338  737.881  556.412  420.891  405.666
  309.269  274.475  178.611  169.764  129.429   88.9     56.797 -918.013]
[-917.9   56.