In [1]:
import pickle
import pprint

# load database.pickle
filename = "testcases/database.pickle"
with open(filename, "rb") as f:
    database = pickle.load(f)

# show the data structure of database
"""
Data structure of database:

database: dict
{
    <calc_name>:{
        <method_0>: <Molecules object>,
        <method_1>: <Molecules object>,
        
    },

}

"""
pprint.pprint(database)


{'Alkoxyl': {'B3LYP': Molecules(symbols='CCl2F2CHO', pbc=False),
             'G4': Molecules(symbols='CCl2F2CHO', pbc=False),
             'MP2-FC': Molecules(symbols='CCl2F2CHO', pbc=False)},
 'Alkoxyl-ClLeave-CF2ClCH0': {'B3LYP': Molecules(symbols='CF2CHOCl', pbc=False),
                              'G4': Molecules(symbols='CF2CHOCl', pbc=False),
                              'MP2-FC': Molecules(symbols='CF2CHOCl', pbc=False)},
 'Alkoxyl-ClLeave_ts': {'B3LYP': Molecules(symbols='CClF2CHOCl', pbc=False),
                        'G4': Molecules(symbols='CClF2CHOCl', pbc=False),
                        'MP2-FC': Molecules(symbols='CClF2CHOCl', pbc=False)},
 'Alkoxyl-HLeave-CClF2C(O)Cl': {'B3LYP': Molecules(symbols='CCl2F2CO', pbc=False),
                                'G4': Molecules(symbols='CCl2F2CO', pbc=False),
                                'MP2-FC': Molecules(symbols='CCl2F2CO', pbc=False)},
 'Alkoxyl-HLeave_O2_ts': {'B3LYP': Molecules(symbols='CCl2F2CHO3', pbc=False),
       

In [2]:
# some setting for pretty printing
import numpy as np
import pandas as pd
np.set_printoptions(precision=3)
pd.set_option("display.chop_threshold", 3)
pd.set_option('display.width', 80)
pd.set_option('display.max_rows', 10)
pd.set_option('display.max_columns', 6)


# show one example in data
print(database["HCFC132b-OH_ts"])
mol = database["HCFC132b-OH_ts"]["B3LYP_hindrot"] # G4 or MP2,MP2(FC) or B3LYP
mol_1 = database["HCFC132b-OH_ts"]["B3LYP"] # G4 or MP2,MP2(FC) or B3LYP
print(type(mol))
# Molecules is an object storing g16 calculation results
# show the basic information (inherited from ase.Atoms)
print(f"Formula: {mol.get_chemical_formula()}")
print(f"Sybmols: {mol.get_chemical_symbols()}")
print("Geometry:")
print(mol.get_positions())


# show the calculation infomation
print(f"Method: {mol.method}")
print(mol.hinderedrotor())
print(type(mol.hinderedrotor()))
print(mol_1.hinderedrotor())
print(mol_1.hinderedrotor() == [])
print(mol.logpath)
print(mol_1.logpath)
# print(f"Basis sets: {mol.basis}") # Bugs
# print(f"Electronic energy(hartree): {mol.electronic_energy}")
# print(f"Is TS calculation? {mol.ts}")
# print("Frequencies(cm-1):")
print(mol.frequencies)
print(mol_1.frequencies)
print(f"ZPE(hartree): {mol.zpe}")
print(f"ZPE(hartree): {mol_1.zpe}")
# print(f"Anharmonic ZPE(hartree): {mol.anharm_zpe}")
# print("Anharminic matrix:")
# print(pd.DataFrame(mol.anharm_matrix))


{'B3LYP_hindrot': Molecules(symbols='CH2CCl2F2OH', pbc=False), 'MP2-FC': Molecules(symbols='CH2CCl2F2OH', pbc=False), 'B3LYP': Molecules(symbols='CH2CCl2F2OH', pbc=False), 'G4': Molecules(symbols='CH2CCl2F2OH', pbc=False)}
<class 'gausskit.molecules.Molecules'>
Formula: C2H3Cl2F2O
Sybmols: ['C', 'H', 'H', 'C', 'Cl', 'Cl', 'F', 'F', 'O', 'H']
Geometry:
[[ 0.     0.     0.   ]
 [ 0.     0.     1.208]
 [ 1.042  0.    -0.314]
 [-0.739  1.251 -0.448]
 [ 0.218  2.705  0.019]
 [-0.809 -1.476 -0.527]
 [-0.926  1.274 -1.767]
 [-1.94   1.328  0.141]
 [-0.223  0.239  2.49 ]
 [-1.14   0.56   2.442]]
Method: B3LYP
[11.439  1.864  0.981]
<class 'numpy.ndarray'>
[]
True
/home/yuflin/dev/Gausskit/data/HCFC132b-OH_ts.log
/home/yuflin/dev/Gausskit/data/20221023-RP_B3LYP_anharm/HCFC132b/HCFC132b-OH_ts.log
[-917.9   56.8   88.8  129.4  169.7  178.5  274.4  309.2  405.6  420.8
  556.4  737.8  769.3  781.9  853.7  930.6 1007.4 1093.2 1217.7 1235.
 1289.  1463.2 3153.6 3734.3]
[3734.302 3153.702 1463.225 128

In [12]:
from gausskit.molecules import Molecules
import json

with open("testcases/database.json") as f:
    database_dict = json.load(f)

database = {}
for item in database_dict:
    database[item] = {}
    for method in database_dict[item]:
        database[item][method] = Molecules.from_dict(database_dict[item][method])

print(database)


{'HCFC132b-OH_ts': {'B3LYP_hindrot': Molecules(symbols='CH2CCl2F2OH', pbc=False), 'MP2-FC': Molecules(symbols='CH2CCl2F2OH', pbc=False), 'B3LYP': Molecules(symbols='CH2CCl2F2OH', pbc=False), 'G4': Molecules(symbols='CH2CCl2F2OH', pbc=False)}, 'HCFC132b-Cl_ts': {'MP2-FC': Molecules(symbols='CH2CCl2F2Cl', pbc=False), 'B3LYP': Molecules(symbols='CH2CCl2F2Cl', pbc=False), 'G4': Molecules(symbols='CH2CCl2F2Cl', pbc=False)}, 'Radical132b': {'MP2-FC': Molecules(symbols='CHCCl2F2', pbc=False), 'B3LYP': Molecules(symbols='CHCCl2F2', pbc=False), 'G4': Molecules(symbols='CHCCl2F2', pbc=False)}, 'HCFC132b': {'MP2-FC': Molecules(symbols='CH2CCl2F2', pbc=False), 'B3LYP': Molecules(symbols='CH2CCl2F2', pbc=False), 'G4': Molecules(symbols='CH2CCl2F2', pbc=False)}, 'HCFC133a': {'MP2-FC': Molecules(symbols='CH2CClF3', pbc=False), 'B3LYP': Molecules(symbols='CH2CClF3', pbc=False), 'G4': Molecules(symbols='CH2CClF3', pbc=False)}, 'HCFC133a-OH_ts': {'MP2-FC': Molecules(symbols='CH2CClF2OHF', pbc=False), 'B