In [11]:
import pickle
import pprint

# load database.pickle
filename = "test/database.pickle"
with open(filename, "rb") as f:
    database = pickle.load(f)

# show the data structure of database
pprint.pprint(database)


{'H2O': {'M062X': Molecules(symbols='OH2', pbc=False)},
 'L2': {'M062X,M062X': Molecules(symbols='OSi2CH3CH3CH3CH3CH3CH3', pbc=False)},
 'L2OH-TSa-4': {'M062X': Molecules(symbols='OSi2CH3CH3CH3CH3CH3CH3OH', pbc=False)},
 'L2R': {'M062X': Molecules(symbols='OSi2CH3CH3CH3CH2CH3CH3', pbc=False)},
 'L2_hindrot': {'M062X_hindrot': Molecules(symbols='OSi2CH3CH3CH3CH3CH3CH3', pbc=False)},
 'OH': {'M062X': Molecules(symbols='OH', pbc=False)}}


In [12]:
# some setting for pretty printing
import numpy as np
import pandas as pd
np.set_printoptions(precision=3)
pd.set_option("display.chop_threshold", 3)
pd.set_option('display.width', 80)
pd.set_option('display.max_rows', 10)
pd.set_option('display.max_columns', 6)


# show one example in data
print(database["L2OH-TSa-4"])
mol = database["L2_hindrot"]["M062X_hindrot"] # G4 or MP2,MP2(FC) or B3LYP
# hint:  for  "HCFC132b-OH_ts":
#                 "B3LYP_hindrot":  example with hindered rotor calculation
#                 "B3LYP":          example with anharmonic vibrations
#                 "MP2,MP2(FC)":    example with anharmonic vibrations



# show the basic information (inherited from ase.Atoms)
print(f"Formula: {mol.get_chemical_formula()}")
print(f"Sybmols: {mol.get_chemical_symbols()}")
print("Geometry:")
print(mol.get_positions())


# show the calculation infomation
print(f"Method: {mol.method}")
print(mol.logpath)
# print(f"Basis sets: {mol.basis}") # Bugs
print(f"Electronic energy(hartree): {mol.electronic_energy}")
print(f"Is TS calculation? {mol.ts}")
print("Frequencies(cm-1):")
print(mol.frequencies)
print(f"ZPE(hartree): {mol.zpe}")
print(f"Anharmonic ZPE(hartree): {mol.anharm_zpe}")
print("Anharminic matrix:")
print(pd.DataFrame(mol.anharm_matrix))


# hindered rotor
mol_hindrot = mol.hinderedrotor
if mol_hindrot != []:
    print("Hindered rotor information")
    print("Reduced momentums (amu*Bohr**2)")
    print(mol_hindrot._reduced_moms)
    print("Rotating bond")
    print(mol_hindrot._rotating_bonds)
    print("Rotating atoms")
    print(mol_hindrot._rotating_groups)
    print("In replacement of these vibrations")
    print(mol_hindrot._corrected_vibs)
    print(mol_hindrot._symmetry_numbers)

{'M062X': Molecules(symbols='OSi2CH3CH3CH3CH3CH3CH3OH', pbc=False)}
Formula: C6H18OSi2
Sybmols: ['O', 'Si', 'Si', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Geometry:
[[ 0.268  0.467  0.418]
 [ 1.86   0.06   0.577]
 [-0.659  1.814  0.189]
 [ 2.005 -1.779  0.299]
 [ 1.658 -2.048 -0.699]
 [ 3.04  -2.111  0.399]
 [ 1.402 -2.326  1.025]
 [ 2.442  0.513  2.296]
 [ 2.365  1.589  2.463]
 [ 1.839  0.01   3.053]
 [ 3.483  0.224  2.447]
 [ 2.864  0.999 -0.696]
 [ 3.921  0.738 -0.632]
 [ 2.521  0.773 -1.707]
 [ 2.779  2.077 -0.545]
 [-2.416  1.375  0.635]
 [-3.081  2.228  0.496]
 [-2.778  0.557  0.012]
 [-2.483  1.06   1.677]
 [-0.547  2.339 -1.604]
 [ 0.477  2.603 -1.87 ]
 [-0.87   1.533 -2.264]
 [-1.179  3.207 -1.798]
 [-0.023  3.191  1.289]
 [-0.051  2.895  2.339]
 [ 1.008  3.449  1.039]
 [-0.627  4.092  1.177]]
Method: M062X
/home/yuflin/dev/Gausskit/test/data/L2_hindrot.log
Electronic energy(hartree): -893.821798500