In [12]:
import pickle
import pprint

# load database.pickle
filename = "testcases/database.pickle"
with open(filename, "rb") as f:
    database = pickle.load(f)

# show the data structure of database
"""
Data structure of database:

database: dict
{
    <calc_name>:{
        <method_0>: <Molecules object>,
        <method_1>: <Molecules object>,
        
    },

}

"""
pprint.pprint(database)


{'Alkoxyl': {'B3LYP': Molecules(symbols='CCl2F2CHO', pbc=False),
             'G4': Molecules(symbols='CCl2F2CHO', pbc=False),
             'MP2-FC': Molecules(symbols='CCl2F2CHO', pbc=False)},
 'Alkoxyl-ClLeave-CF2ClCH0': {'B3LYP': Molecules(symbols='CF2CHOCl', pbc=False),
                              'G4': Molecules(symbols='CF2CHOCl', pbc=False),
                              'MP2-FC': Molecules(symbols='CF2CHOCl', pbc=False)},
 'Alkoxyl-ClLeave_ts': {'B3LYP': Molecules(symbols='CClF2CHOCl', pbc=False),
                        'G4': Molecules(symbols='CClF2CHOCl', pbc=False),
                        'MP2-FC': Molecules(symbols='CClF2CHOCl', pbc=False)},
 'Alkoxyl-HLeave-CClF2C(O)Cl': {'B3LYP': Molecules(symbols='CCl2F2CO', pbc=False),
                                'G4': Molecules(symbols='CCl2F2CO', pbc=False),
                                'MP2-FC': Molecules(symbols='CCl2F2CO', pbc=False)},
 'Alkoxyl-HLeave_O2_ts': {'B3LYP': Molecules(symbols='CCl2F2CHO3', pbc=False),
       

In [13]:
# some setting for pretty printing
import numpy as np
import pandas as pd
np.set_printoptions(precision=3)
pd.set_option("display.chop_threshold", 3)
pd.set_option('display.width', 80)
pd.set_option('display.max_rows', 10)
pd.set_option('display.max_columns', 6)


# show one example in data
print(database["HCFC132b-OH_ts"])
mol = database["HCFC132b-OH_ts"]["B3LYP-1"] # G4 or MP2,MP2(FC) or B3LYP
print(type(mol))
# Molecules is an object storing g16 calculation results
# show the basic information (inherited from ase.Atoms)
print(f"Formula: {mol.get_chemical_formula()}")
print(f"Sybmols: {mol.get_chemical_symbols()}")
print("Geometry:")
print(mol.get_positions())


# show the calculation infomation
print(f"Method: {mol.method}")
print(mol.hinderedrotor())
print(f"Basis sets: {mol.basis}") # Bugs
print(f"Electronic energy(hartree): {mol.electronic_energy}")
print(f"Is TS calculation? {mol.ts}")
print("Frequencies(cm-1):")
print(mol.frequencies)
print(f"ZPE(hartree): {mol.zpe}")
print(f"Anharmonic ZPE(hartree): {mol.anharm_zpe}")
print("Anharminic matrix:")
print(pd.DataFrame(mol.anharm_matrix))


{'B3LYP': Molecules(symbols='CH2CCl2F2OH', pbc=False), 'MP2-FC': Molecules(symbols='CH2CCl2F2OH', pbc=False), 'B3LYP-1': Molecules(symbols='CH2CCl2F2OH', pbc=False), 'G4': Molecules(symbols='CH2CCl2F2OH', pbc=False)}
<class 'gausskit.molecules.Molecules'>
Formula: C2H3Cl2F2O
Sybmols: ['C', 'H', 'H', 'C', 'Cl', 'Cl', 'F', 'F', 'O', 'H']
Geometry:
[[ 0.     0.     0.   ]
 [ 0.     0.     1.208]
 [ 1.042  0.    -0.314]
 [-0.739  1.251 -0.448]
 [ 0.218  2.705  0.019]
 [-0.809 -1.476 -0.527]
 [-0.926  1.274 -1.767]
 [-1.94   1.328  0.141]
 [-0.223  0.239  2.49 ]
 [-1.14   0.56   2.442]]
Method: B3LYP
[11.439  1.864  0.981]
basis sets are not set
Basis sets: None
Electronic energy(hartree): -1273.24249443
Is TS calculation? True
Frequencies(cm-1):
[-917.9   56.8   88.8  129.4  169.7  178.5  274.4  309.2  405.6  420.8
  556.4  737.8  769.3  781.9  853.7  930.6 1007.4 1093.2 1217.7 1235.
 1289.  1463.2 3153.6 3734.3]
ZPE(hartree): 0.047517
anharmonic zero point energy is not set
Anharmonic ZPE